final int NUMBER_DAYS_LAST_CIGARETTES_SMOKED = 15;
final double WEEKLY_REDUCTION_PERCENTAGE = 0.4;
final double DAY_HOURS = 24;
final double AWAKE_HOURS = 17;
final double SLEEP_HOURS = DAY_HOURS - AWAKE_HOURS;
final int NOTIFICATION_FREQUENCY = 4;
